import matplotlib.pyplot as plt
from src.RandomAllocation import hotel_status

# Hotel revenue
hotel_ids = list(hotel_status.keys())
revenues = [hotel_status[hotel_id]['revenue'] for hotel_id in hotel_ids]

# Plot
plt.figure(figsize=(10, 6))
plt.bar(hotel_ids, revenues, color='skyblue')
plt.title("Revenue Generated by Each Hotel")
plt.xlabel("Hotel ID")
plt.ylabel("Revenue ($)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# Example data: room allocation
rooms_allocated = [hotels_dict[hotel_id]['available_rooms'] - hotel_status[hotel_id]['remaining_rooms'] for hotel_id in hotel_ids]

# Plot
plt.figure(figsize=(8, 8))
plt.pie(rooms_allocated, labels=hotel_ids, autopct='%1.1f%%', startangle=90, colors=plt.cm.tab20.colors)
plt.title("Proportion of Rooms Allocated per Hotel")
plt.show()
